// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx4WrAjnT8qDa9kafcx9yTkEkrhhNZmXU',
    appId: '1:699140970310:web:5bae0711e923e917cdf747',
    messagingSenderId: '699140970310',
    projectId: 'alpha-23ca8',
    authDomain: 'alpha-23ca8.firebaseapp.com',
    storageBucket: 'alpha-23ca8.appspot.com',
    measurementId: 'G-124GJ1EQMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzNgH9GtH5d5Y3yqU42Bj3ElMjZxH-QAA',
    appId: '1:699140970310:android:4cf6a64396e19dcccdf747',
    messagingSenderId: '699140970310',
    projectId: 'alpha-23ca8',
    storageBucket: 'alpha-23ca8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8TgBIuUG3qt0wOEBJghymqUjZtBlT3SI',
    appId: '1:699140970310:ios:018b0fb266561de0cdf747',
    messagingSenderId: '699140970310',
    projectId: 'alpha-23ca8',
    storageBucket: 'alpha-23ca8.appspot.com',
    iosBundleId: 'com.example.alpha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8TgBIuUG3qt0wOEBJghymqUjZtBlT3SI',
    appId: '1:699140970310:ios:018b0fb266561de0cdf747',
    messagingSenderId: '699140970310',
    projectId: 'alpha-23ca8',
    storageBucket: 'alpha-23ca8.appspot.com',
    iosBundleId: 'com.example.alpha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx4WrAjnT8qDa9kafcx9yTkEkrhhNZmXU',
    appId: '1:699140970310:web:437291bb5c417bf5cdf747',
    messagingSenderId: '699140970310',
    projectId: 'alpha-23ca8',
    authDomain: 'alpha-23ca8.firebaseapp.com',
    storageBucket: 'alpha-23ca8.appspot.com',
    measurementId: 'G-M1G7RQ2TVB',
  );
}
